### ISSUE TITLE
Caching table data

### ISSUE THREAD

**Issue by bengoshow** [smadeira/ministry-platform-api#6]
Hi @smadeira,
I've implemented your solution and I can see that it's caching the OAuth token, but I wonder how hard it would be to cache the data that's being returned as well?

**Comment by smadeira** [comment]
Let me look at it and get back to you. I don't think it would be too hard
to do.

**Comment by smadeira** [comment]
I re-read your question and am not 100% sure what you are asking for. Can you give me a quick use case or scenario that lets me know what you are trying to do?

**Comment by bengoshow** [comment]
Trying to cache results returned from the Table endpoint. I’m using the API to display event data on a website.

**Comment by smadeira** [comment]
I had no plans on caching the data.  I always assumed that was an
application thing and not the API wrapper.

If the API wrapper did cache the data, how would you envision it working?

-------------------------------------------------
Scott Madeira

**Comment by bengoshow** [comment]
Is rate limiting from the API a concern? That's where the question originated for me, but then potential service outages were another issue prompting the question of caching data from the API.

**Comment by oneseventeen** [comment]
I think I would lean personally towards a separate package doing caching that depends on this one, but mainly because I love the idea of this API being light and manageable enough that Scott doesn't get tired of maintaining it. ;)

I like making my own classes that extend this API for different data types (like events) so my code primarily runs something like:
`$events = Events::thisMonth();`

Events would be a class that extends MP and authenticates against the API, and runs the queries to pull this month's events.  That class could also handle the caching, that way I could cache using Redis whereas you may want to use MySQL.

**Comment by smadeira** [comment]
I like Chris's idea of caching as a separate package where you can pick the cache mechanism that suits your needs. If I get time I may put some samples together.
